### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by graham768** [thebinarypenguin/socket.io-chess#12]
After npm install, I run the server and get the following:
```
/Users/ben/socket.io-chess/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/ben/socket.io-chess/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ben/socket.io-chess/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:573:32)
```

**Comment by thebinarypenguin** [comment]
This is because you are using a current version of Node (v6 or later) to run old code. It should still work on the outdated v4.

I'll have to refactor the Express bits to use v4 instead of v3

**Comment by thebinarypenguin** [comment]
This project has been abandoned. See #15
